import Head from 'next/head'
//import Image from 'next/image'
import { useRouter } from 'next/router';
import { supabaseClient } from '../utils/supabase'
import {useAuth, useUser} from '@clerk/nextjs'
import { useState } from 'react'

export default function Create() {
    const {getToken} = useAuth()
    const {user} = useUser()
    
    const [title, setTitle] = useState('')
    const [category, setCategory] = useState('')
    const [ingredients, setIngredients] = useState('');
    const [instructions, setInstructions] = useState('');

    const router = useRouter()
    
    
    const handleSubmit = async (e: any) => {
        e.preventDefault();
        const supabaseToken = await getToken({template: 'supabase'})
        const supabase = await supabaseClient(supabaseToken!)
        const{data, error} = await supabase.from('recipes').insert({
            user_id: user?.id,
            recipe_creator: user?.fullName,
            title: title,
            category: category,
            ingredients: ingredients,
            instructions: instructions,
        })
        //console.log('DATA:', data)
        //console.log('ERROR:', error)
        router.push('/')
    }
  return (
    <div className='h-screen flex justify-center bg-slate-900'>
        <Head>
            <title>Add Recipe</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/recipes.svg" />
        </Head>
        <form 
            onSubmit={handleSubmit}
            className='mt-10 mb-20 bg-slate-200 w-[80%] p-5 rounded-lg'
        >
            <div className='flex justify-between'>
                <div className='flex flex-col'>
                    <label htmlFor='recipe-name'>Recipe Name</label>
                    <input 
                        type='text'
                        value={title}
                        onChange={(e) => setTitle(e.target.value)}
                        className='input input-bordered w-80 mb-5 bg-slate-50'
                    ></input>
                </div>
                <div className='flex flex-col'>
                    <label htmlFor='recipe-name'>Category</label>
                    <select
                        value={category}
                        onChange={(e) => setCategory(e.target.value)}
                        className='input input-bordered w-30 bg-slate-50'
                    >
                        <option value="">Select</option>
                        <option value="Asian">Asian</option>
                        <option value="Baking">Baking</option>
                        <option value="Meat">Meat</option>
                        <option value="Miscellaneous">Miscellaneous</option>
                        <option value="Pasta">Pasta</option>
                        <option value="Rice Dishes">Rice Dishes</option>
                        <option value="Seafood">Seafood</option>
                        <option value="Stews">Stews</option>
                        <option value="Vegetables">Vegetables</option>
                    </select>
                </div>
            </div>
            <div className='flex'>
                <div className='flex flex-col w-[40%] mr-5'>
                    <label htmlFor='ingredients'>Ingredients</label>
                    <textarea
                        value={ingredients}
                        onChange={(e) => setIngredients(e.target.value)}
                        className='h-[300px] input input-bordered bg-slate-50'
                    ></textarea>
                </div>
                <div className='flex flex-col w-[60%]'>
                    <label htmlFor='recipe-steps'>Instructions</label>
                    <textarea
                        value={instructions}
                        onChange={(e) => setInstructions(e.target.value)}
                        className='h-[300px] input input-bordered bg-slate-50'
                    ></textarea>
                </div>
            </div>
            <div className='flex justify-start mt-8'>
                <button 
                    type='submit' 
                    className='inline-block px-4 py-3
                    text-lg font-semibold text-center
                    text-white uppercase transition
                    duration-200 ease-in-out bg-indigo-600 
                    rounded-md cursor-pointer
                    hover:bg-indigo-700 w-[150px]'
                >Save</button>
            </div>
        </form>
    </div>
  )
}
