import Head from 'next/head'
import Link from "next/link"

import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';

import { supabaseClient } from '../utils/supabase'
import {useAuth, useUser} from '@clerk/nextjs'

import {AiFillGithub} from 'react-icons/ai'


export default function Home() {
  const {getToken} = useAuth()
  //const {user} = useUser()

  const [recipeData, setRecipeData] = useState<any[]>([]);
  const [category, setCategory] = useState('all');

  const router = useRouter();

  useEffect(() => {
    async function fetchData() {

      const supabaseToken = await getToken({template: 'supabase'})
      const supabase = await supabaseClient(supabaseToken!)

      let query = supabase.from('recipes').select();
      if(category !== 'all'){
        query = query.eq('category', category)
      }
    
      const rows = await query.order('title')
      setRecipeData(rows.data!);
    }
    fetchData();
  }, [category]);

  return (
    <div className='flex flex-col w-full items-center'>
      <Head>
        <title>Recipes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/recipes.svg" />
      </Head>
      <div className='mt-16'>
        <label className="block text-sm font-medium leading-5 text-gray-700">
          Category
        </label>
        <div className="relative rounded-md shadow-sm">
          <select value={category} onChange={(e) => 
            setCategory(e.target.value)} 
              className="form-input py-2 px-3 block leading-5 rounded-md 
                transition duration-150 ease-in-out bg-white border 
                border-gray-300 focus:outline-none 
                focus:shadow-outline-blue focus:border-blue-300"
          >
            <option value="all">All</option>
            <option value="Asian">Asian</option>
            <option value="Baking">Baking</option>
            <option value="Meat">Meat</option>
            <option value="Miscellaneous">Miscellaneous</option>
            <option value="Pasta">Pasta</option>
            <option value="Rice Dishes">Rice Dishes</option>
            <option value="Seafood">Seafood</option>
            <option value="Stews">Stews</option>
            <option value="Vegetables">Vegetables</option>
          </select>
        </div>
      </div>
      
      <div className='mt-10 w-11/12 h-auto flex flex-wrap bg-slate-50 p-2 rounded-lg shadow-md'>
          {recipeData.map((recipe, index) => (
            <div
              className='cursor-pointer text-xl w-[197px] ml-2'
              key={index}
              onClick={() => router.push(`/recipe?id=${recipe.id}&title=${recipe.title}&category=${recipe.category}&ingredients=${recipe.ingredients}&instructions=${recipe.instructions}`)}
            >
              {recipe.title}
            </div>
          ))}
      </div>
      <Link href='/add-recipe'>
        <button 
          className='inline-block mt-20 px-4 py-3
          text-sm font-semibold text-center
          text-white uppercase transition
          duration-200 ease-in-out bg-indigo-600 
          rounded-md cursor-pointer
          hover:bg-indigo-700 max-w-lg'
        >Add Recipe</button>
      </Link> 
      <a
        href="https://github.com/jergra/recipes-next-js-clerk-supabase"
        target='_blank'
        rel='noreferrer'
        className='mt-40 text-gray-800'
      >
        <AiFillGithub size={40} />
      </a>
    </div> 
  )
}
