import Head from 'next/head'
import Link from "next/link"

import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';

import { supabaseClient } from '../utils/supabase'
import {useAuth, useUser} from '@clerk/nextjs'

import {AiFillGithub} from 'react-icons/ai'


export default function Home() {

  const {getToken} = useAuth()
  //const {user} = useUser()

  const [recipeData, setRecipeData] = useState<any[]>([]);
  const [category, setCategory] = useState('all');

  const router = useRouter();

  useEffect(() => {
    async function fetchData() {

      const supabaseToken = await getToken({template: 'supabase'})
      const supabase = await supabaseClient(supabaseToken!)

      let query = supabase.from('recipes').select();
      if(category !== 'all'){
        query = query.eq('category', category)
      }
    
      const rows = await query.order('title')
      setRecipeData(rows.data!);
    }
    fetchData();
  }, [category]);

  return (
    <div className='flex flex-col w-full h-screen items-center justify-between bg-gray-900'>
      <Head>
        <title>Recipes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/recipes.svg" />
      </Head>
      <main className='flex flex-col w-full items-center'>
        <div className='mt-12'>
          <div className="relative rounded-md">
            <select value={category} onChange={(e) => 
              setCategory(e.target.value)} 
                className="form-input py-2 px-3 block leading-5 rounded-md 
                  transition duration-150 ease-in-out bg-slate-50 border 
                  border-slate-300 focus:outline-none 
                  focus:shadow-outline-blue focus:border-indigo-300"
            >
              <option value="all">All</option>
              <option value="Asian">Asian</option>
              <option value="Baking">Baking</option>
              <option value="Meat">Meat</option>
              <option value="Miscellaneous">Miscellaneous</option>
              <option value="Pasta">Pasta</option>
              <option value="Rice Dishes">Rice Dishes</option>
              <option value="Seafood">Seafood</option>
              <option value="Stews">Stews</option>
              <option value="Vegetables">Vegetables</option>
            </select>
          </div>
        </div>
        
        <div className='mt-10 w-11/12 h-fit flex flex-wrap bg-slate-50 p-2 rounded-lg'>
            {recipeData.map((recipe, index) => (
              <div
                className='cursor-pointer text-xl w-[195px] ml-2'
                key={index}
                onClick={() => router.push(`/recipe?id=${recipe.id}`)}
              >
                {recipe.title}
              </div>
            ))}
        </div>
        <Link href='/add-recipe'>
          <button 
            className='inline-block mt-20 px-4 py-3
            text-sm font-semibold text-center
            text-white uppercase transition
            duration-200 ease-in-out bg-indigo-600 
            rounded-md cursor-pointer
            hover:bg-indigo-700 max-w-lg'
          >Add Recipe</button>
        </Link> 
      </main>
      <footer className='mb-5'>
        <a
          href="https://github.com/jergra/recipes-next-js-clerk-supabase"
          target='_blank'
          rel='noreferrer'
          className='text-slate-300'
        >
          <AiFillGithub size={40} />
        </a>
      </footer>
    </div> 
  )
}
