import Head from 'next/head'
import Image from 'next/image'

export default function Review() {
  return (
    <div>
      <Head>
        <title>Recipes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>REVIEW</div>
    </div>
  )
}
